#define GTSPS_IMPLEMENTATION
#include "GetTimeSinceProcessStart.h"

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#if VULKAN_HPP_DISPATCH_LOADER_DYNAMIC == 1
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
#endif
